name: Release

on:
  push:
    paths:
      - package.json
      - .github/workflows/gh-release.yml

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i && bun run build

      - name: Create release with tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(cat package.json | jq -r '.version')
          echo $version

          tag_version=$(git tag -l | grep $version)
          echo $tag_version

          # exit if tag already exists
          if [ -n "$tag_version" ]; then
            echo "Tag $version already exists"
            exit 1
          fi

          echo "Creating tag $version"
          git tag $version
          git push --tags

          echo "Creating release $version"
          gh release create -t $version -n "Release $version" $version dist/*

