name: Release

on:
  push:
    paths:
      - package.json
      - .github/workflows/gh-release.yml
      - .github/workflows/release-tag.sh

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: System dependencies
        run: sudo apt update && sudo apt install jq git grep

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i && bun run build

      - name: Create release with tag
        run: sh .github/workflows/release-tag.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}

