name: Release

on:
  push:
    tags:
    - '*'

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i && bun run build

      - name: Create release with tag
        run: gh release create ${{ github.ref }} -t ${{ github.ref }} -n "Release ${{ github.ref }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}

